### PR TITLE
Clickhouse: change defaults for batch sizes

### PR DESCRIPTION
**Pull request by Amogh-Bharadwaj**
Change snapshot num rows per partition and max batch size defaults in UI to 100K instead of 1 Mil

### CODE REVIEW

**Comment by iskakaushik** [comment]
1. Change CDC batch size to 500K
2. Change QRep batch size to 250L
3. Have an dyn conf var `PEERDB_CLICKHOUSE_EXPERIMENTAL_S3_IIS_PARTS` default to `1` if 1 do whatever is happening now, if > 2 use that as `numParts` for both CDC and Qrep.

**Comment by heavycrystal** [comment]
probably better to use negative values/0 to indicate disabled and positive values to indicate `numParts`

**Comment by Amogh-Bharadwaj** [comment]
QRep batch size is already 100K @iskakaushik

**Review by serprex — APPROVED** [review]

**Comment by serprex** [comment]
https://github.com/ClickHouse/data-plane-application/pull/12971 I'll make PR

**Comment by heavycrystal** [comment]
not necessary right now

**Pull request closed without merging**
