### PR TITLE
 Enable wal heartbeats by default

### PR DESCRIPTION
**Pull request by serprex**
users predating PG14 should change the query or disable wal heartbeats

### CODE REVIEW

**Review by iamKunalGupta — APPROVED** [review]
let's test and merge

**Comment by serprex** [comment]
Sending updated LSN & logging that updated LSN. PG is ignoring when we send unrequested standby status updates with updated LSN

**Review by heavycrystal — APPROVED** [review]

**Comment by iamKunalGupta** [comment]
@serprex do we need to send `WalFlushPosition` instead for RDS?

**Comment by iamKunalGupta** [comment]
> @serprex do we need to send `WalFlushPosition` instead for RDS?

nvm, the library does it for us

**Review by heavycrystal — APPROVED** [review]

**Pull request merged**
