### PR TITLE
[snowflake] Run merges in parallel during normalize flow

### PR DESCRIPTION
**Pull request by iskakaushik**
Required by customer

### CODE REVIEW

**Comment by serprex** [comment]
Is this purely perf related? Was this inspired by a customer experience or is this preemptive?

**Comment by iskakaushik** [comment]
> Is this purely perf related? Was this inspired by a customer experience or is this preemptive?

This was identified as a blocker for a customer. They needed lower latencies than the current state of the world. We also identified `MERGE` as the root cause for the problem.

**Comment by heavycrystal** [comment]
decreases overall durability since normalize is not transactional anymore, should be revisited in the future

**Comment by heavycrystal** [comment]
also consider later if this should be configurable on a peer/mirror basis

**Review by heavycrystal — APPROVED** [review]

**Pull request merged**
