### PR TITLE
don't call getMaxSyncsPerCDCFlow in loop

### PR DESCRIPTION
**Pull request by serprex**
this was spamming temporal history

### CODE REVIEW

**Comment by heavycrystal** [comment]
defeats the purpose of it being dynconf

**Comment by serprex** [comment]
it doesn't, dynconf has ui, pause/unpause takes on change. Soft pause should be implemented separately

**Review by iskakaushik — APPROVED** [review]

**Comment by serprex** [comment]
alternatively, use https://pkg.go.dev/go.temporal.io/sdk/workflow#MutableSideEffect

**Comment by serprex** [comment]
prodding more, MutableSideEffect is taking workflow.Context & passing down workflow.Context, creating context.Context with deadline which is scoped by calling context.Context isn't straightforward

**Pull request merged**
